//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace товары
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public string Название { get; set; }
        public string Категория { get; set; }
        public decimal Цена { get; set; }
        public string Размер { get; set; }
        public byte[] image { get; set; }
        public int Количество { get; set; }
    
        public virtual Категория Категория1 { get; set; }
    }
}
